queue_rules:
  - name: default
    queue_conditions:
      - check-success=my_one_minute_CI
    priority_rules:
      - name: high priority
        conditions:
          - label=urgent
        priority: high

pull_request_rules:
  - name: automatic merge
    conditions:
      - base=main
    actions:
      queue:
